/**
 * Core transcript fetching logic using yt-dlp
 */

import { exec } from "child_process";
import { promisify } from "util";
import { writeFile, unlink, mkdtemp } from "fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { TranscriptParser, TranscriptSnippet } from "./parser.js";
import {
  YtDlpNotFoundError,
  YtDlpError,
  TranscriptNotFoundError,
  VideoUnavailableError,
} from "./errors.js";
import { extractVideoInfo } from "./url-detector.js";

const execAsync = promisify(exec);

export interface TranscriptLanguage {
  code: string;
  name: string;
  isAutoGenerated?: boolean;
}

export interface TranscriptResult {
  snippets: TranscriptSnippet[];
  url: string;
  language?: string;
  languageCode?: string;
  isGenerated?: boolean;
}

export interface TranscriptFetcherOptions {
  ytDlpPath?: string;
  debug?: boolean;
}

/**
 * Main class for fetching video transcripts using yt-dlp
 */
export class TranscriptFetcher {
  private ytDlpPath: string;
  private debug: boolean;
  private parser: TranscriptParser;

  constructor(options: TranscriptFetcherOptions = {}) {
    this.ytDlpPath = options.ytDlpPath || "yt-dlp";
    this.debug = options.debug || false;
    this.parser = new TranscriptParser();
  }

  /**
   * Log debug information
   */
  private log(...args: unknown[]): void {
    if (this.debug) {
      console.error("[transcript-fetcher]", ...args);
    }
  }

  /**
   * Checks if yt-dlp is available
   */
  async checkYtDlpAvailable(): Promise<boolean> {
    try {
      const { stdout } = await execAsync(`${this.ytDlpPath} --version`);
      this.log("yt-dlp version:", stdout.trim());
      return true;
    } catch (error) {
      this.log("yt-dlp check failed:", error);
      return false;
    }
  }

  /**
   * Lists all available transcript languages for a video
   */
  async listLanguages(url: string): Promise<TranscriptLanguage[]> {
    // Ensure yt-dlp is available
    if (!(await this.checkYtDlpAvailable())) {
      throw new YtDlpNotFoundError();
    }

    this.log(`Listing languages for: ${url}`);

    try {
      // Use --list-subs to get available subtitles
      const command = `${this.ytDlpPath} --list-subs --skip-download "${url}"`;
      this.log(`Executing: ${command}`);

      const { stdout, stderr } = await execAsync(command, {
        maxBuffer: 10 * 1024 * 1024, // 10MB buffer
      });

      this.log("yt-dlp stdout:", stdout);
      if (stderr) {
        this.log("yt-dlp stderr:", stderr);
      }

      // Parse the output to extract language information
      const languages = this.parseLanguageList(stdout, url);

      if (languages.length === 0) {
        // Check if video is unavailable
        if (
          stdout.includes("Video unavailable") ||
          stdout.includes("Private video")
        ) {
          throw new VideoUnavailableError(url);
        }
        throw new TranscriptNotFoundError(
          url,
          "No subtitles found in yt-dlp output",
        );
      }

      return languages;
    } catch (error) {
      if (
        error instanceof YtDlpNotFoundError ||
        error instanceof VideoUnavailableError ||
        error instanceof TranscriptNotFoundError
      ) {
        throw error;
      }

      const errorMessage =
        error instanceof Error ? error.message : String(error);
      this.log("Error listing languages:", errorMessage);

      // Check for common error patterns
      if (
        errorMessage.includes("Video unavailable") ||
        errorMessage.includes("Private video")
      ) {
        throw new VideoUnavailableError(url);
      }

      if (
        errorMessage.includes("No subtitles") ||
        errorMessage.includes("Subtitles not available")
      ) {
        throw new TranscriptNotFoundError(url);
      }

      throw new YtDlpError(url, errorMessage);
    }
  }

  /**
   * Parses yt-dlp --list-subs output to extract language information
   */
  private parseLanguageList(output: string, url: string): TranscriptLanguage[] {
    const languages: TranscriptLanguage[] = [];
    const lines = output.split("\n");

    // Look for subtitle language lines
    // Format is typically: "Language Name (language_code) - subtitle format"
    // or "Available subtitles for ..."
    let inSubtitleSection = false;

    for (const line of lines) {
      const trimmed = line.trim();

      // Check if we're in the subtitle section
      if (
        trimmed.toLowerCase().includes("available subtitles") ||
        trimmed.toLowerCase().includes("subtitles")
      ) {
        inSubtitleSection = true;
        continue;
      }

      if (!inSubtitleSection) continue;

      // Skip empty lines and separators
      if (!trimmed || trimmed.startsWith("-")) continue;

      // Try to match language patterns
      // Pattern 1: "Language Name (code)" or "Language Name - code"
      const match1 = trimmed.match(
        /^([^(]+?)\s*[\(-]\s*([a-z]{2}(?:-[A-Z]{2})?)/i,
      );
      if (match1) {
        const name = match1[1].trim();
        const code = match1[2].toLowerCase();
        languages.push({
          code,
          name,
          isAutoGenerated:
            name.toLowerCase().includes("auto") ||
            name.toLowerCase().includes("generated"),
        });
        continue;
      }

      // Pattern 2: Just language code
      const match2 = trimmed.match(/^([a-z]{2}(?:-[A-Z]{2})?)\s*[-:]/i);
      if (match2) {
        const code = match2[1].toLowerCase();
        languages.push({
          code,
          name: code,
        });
        continue;
      }
    }

    // If no languages found with patterns, try to extract from yt-dlp JSON output
    if (languages.length === 0) {
      // Sometimes yt-dlp outputs JSON when using --dump-json
      try {
        const jsonMatch = output.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          const json = JSON.parse(jsonMatch[0]);
          if (json.subtitles) {
            for (const [code, subs] of Object.entries(
              json.subtitles as Record<string, unknown[]>,
            )) {
              if (Array.isArray(subs) && subs.length > 0) {
                languages.push({
                  code: code.toLowerCase(),
                  name: code,
                  isAutoGenerated:
                    (subs[0] as { ext?: string }).ext === "vtt" ||
                    code.includes("auto"),
                });
              }
            }
          }
        }
      } catch {
        // Ignore JSON parsing errors
      }
    }

    return languages;
  }

  /**
   * Fetches transcript for a video
   */
  async fetchTranscript(
    url: string,
    options: {
      language?: string;
      format?: "srt" | "vtt" | "json";
    } = {},
  ): Promise<TranscriptResult> {
    // Ensure yt-dlp is available
    if (!(await this.checkYtDlpAvailable())) {
      throw new YtDlpNotFoundError();
    }

    const { language, format = "srt" } = options;
    this.log(
      `Fetching transcript for: ${url}, language: ${language || "default"}, format: ${format}`,
    );

    // Create a temporary directory for subtitle files
    const tempDir = await mkdtemp(join(tmpdir(), "transcript-mcp-"));
    const subtitleFile = join(tempDir, `subtitle.${format}`);

    try {
      // Build yt-dlp command
      const commandParts = [
        this.ytDlpPath,
        "--write-sub",
        "--write-auto-sub", // Include auto-generated subtitles
        "--skip-download",
        `--sub-format`,
        format,
        `--output`,
        subtitleFile.replace(`.${format}`, ""), // yt-dlp adds extension
      ];

      // Add language option if specified, otherwise yt-dlp will use default
      if (language) {
        commandParts.push(`--sub-lang`, language);
      }

      commandParts.push(`"${url}"`);

      const command = commandParts.join(" ");
      this.log(`Executing: ${command}`);

      const { stdout, stderr } = await execAsync(command, {
        maxBuffer: 10 * 1024 * 1024, // 10MB buffer
        cwd: tempDir,
      });

      this.log("yt-dlp stdout:", stdout);
      if (stderr) {
        this.log("yt-dlp stderr:", stderr);
      }

      // Check for errors in output
      if (
        stderr &&
        (stderr.includes("Video unavailable") ||
          stderr.includes("Private video"))
      ) {
        throw new VideoUnavailableError(url);
      }

      if (
        stderr &&
        (stderr.includes("No subtitles") ||
          stderr.includes("Subtitles not available"))
      ) {
        throw new TranscriptNotFoundError(url);
      }

      // Find the actual subtitle file (yt-dlp may add language code to filename)
      const subtitleFiles = await this.findSubtitleFiles(tempDir, format);

      if (subtitleFiles.length === 0) {
        throw new TranscriptNotFoundError(
          url,
          "No subtitle file was created by yt-dlp",
        );
      }

      // Use the first subtitle file found (or prefer the requested language if available)
      let selectedFile = subtitleFiles[0];
      if (language) {
        const langFile = subtitleFiles.find(
          (f) => f.includes(language) || f.includes(language.split("-")[0]),
        );
        if (langFile) {
          selectedFile = langFile;
        }
      }

      this.log(`Reading subtitle file: ${selectedFile}`);

      // Read and parse the subtitle file
      const { readFile } = await import("fs/promises");
      const content = await readFile(selectedFile, "utf-8");

      const snippets = this.parser.parse(content, url);

      if (snippets.length === 0) {
        throw new TranscriptNotFoundError(
          url,
          "Subtitle file is empty or could not be parsed",
        );
      }

      // Extract language info from filename if possible
      const languageMatch = selectedFile.match(/([a-z]{2}(?:-[A-Z]{2})?)/i);
      const detectedLanguage = languageMatch ? languageMatch[1] : language;

      return {
        snippets,
        url,
        languageCode: detectedLanguage,
        language: detectedLanguage,
        isGenerated: selectedFile.toLowerCase().includes("auto"),
      };
    } catch (error) {
      if (
        error instanceof YtDlpNotFoundError ||
        error instanceof VideoUnavailableError ||
        error instanceof TranscriptNotFoundError
      ) {
        throw error;
      }

      const errorMessage =
        error instanceof Error ? error.message : String(error);
      this.log("Error fetching transcript:", errorMessage);

      // Check for common error patterns
      if (
        errorMessage.includes("Video unavailable") ||
        errorMessage.includes("Private video")
      ) {
        throw new VideoUnavailableError(url);
      }

      if (
        errorMessage.includes("No subtitles") ||
        errorMessage.includes("Subtitles not available")
      ) {
        throw new TranscriptNotFoundError(url);
      }

      throw new YtDlpError(url, errorMessage);
    } finally {
      // Clean up temporary directory
      try {
        const { readdir, rm } = await import("fs/promises");
        const files = await readdir(tempDir);
        for (const file of files) {
          await unlink(join(tempDir, file)).catch(() => {
            // Ignore cleanup errors
          });
        }
        await rm(tempDir, { recursive: true, force: true }).catch(() => {
          // Ignore cleanup errors
        });
      } catch {
        // Ignore cleanup errors
      }
    }
  }

  /**
   * Finds subtitle files in a directory
   */
  private async findSubtitleFiles(
    dir: string,
    format: string,
  ): Promise<string[]> {
    const { readdir } = await import("fs/promises");
    const files = await readdir(dir);
    const subtitleFiles: string[] = [];

    for (const file of files) {
      if (
        file.endsWith(`.${format}`) ||
        file.includes("subtitle") ||
        file.includes("sub")
      ) {
        subtitleFiles.push(join(dir, file));
      }
    }

    return subtitleFiles;
  }
}
